version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://peerpods_user:UvLVAlQkzjYkTlgMTPo64H0qRzcM35V7@dpg-d033ttuuk2gs73f160ag-a.oregon-postgres.render.com/peerpods

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"