"""Add creator_id to Pod

Revision ID: 52ea56e472e0
Revises: 1e2672023ae0
Create Date: 2025-04-14 19:48:07.622776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ea56e472e0'
down_revision: Union[str, None] = '1e2672023ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pods', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pods', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pods', type_='foreignkey')
    op.drop_column('pods', 'creator_id')
    # ### end Alembic commands ###
