"""add voice support to messages

Revision ID: d33076b04fc4
Revises: da0777c40f88
Create Date: 2025-04-14 20:45:57.872060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33076b04fc4'
down_revision: Union[str, None] = 'da0777c40f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('voice_path', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('pods', sa.Column('auto_launch_at', sa.DateTime(), nullable=True))
    op.add_column('pods', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('pods', sa.Column('max_voice_message_seconds', sa.Integer(), nullable=True))
    op.add_column('pods', sa.Column('visibility', sa.String(), nullable=True))
    op.add_column('pods', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pods', 'tags')
    op.drop_column('pods', 'visibility')
    op.drop_column('pods', 'max_voice_message_seconds')
    op.drop_column('pods', 'timezone')
    op.drop_column('pods', 'auto_launch_at')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'voice_path')
    # ### end Alembic commands ###
